# Generated by Django 3.2.9 on 2021-11-16 23:13

from django.db import migrations, models
import logging


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteFilm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_title', models.CharField(default=logging.NullHandler, max_length=500)),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FavoritePlanet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(default=logging.NullHandler, max_length=500)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
    ]
